// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/plugins/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty request messages
type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type APIRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIRoutesRequest) Reset() {
	*x = APIRoutesRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRoutesRequest) ProtoMessage() {}

func (x *APIRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRoutesRequest.ProtoReflect.Descriptor instead.
func (*APIRoutesRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{1}
}

type UIManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIManifestRequest) Reset() {
	*x = UIManifestRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIManifestRequest) ProtoMessage() {}

func (x *UIManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIManifestRequest.ProtoReflect.Descriptor instead.
func (*UIManifestRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{2}
}

// Metadata response
type MetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Capabilities  []string               `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *MetadataResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MetadataResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetadataResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *MetadataResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetadataResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// API Routes response
type APIRoutesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*RouteDescriptor     `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIRoutesResponse) Reset() {
	*x = APIRoutesResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRoutesResponse) ProtoMessage() {}

func (x *APIRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRoutesResponse.ProtoReflect.Descriptor instead.
func (*APIRoutesResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *APIRoutesResponse) GetRoutes() []*RouteDescriptor {
	if x != nil {
		return x.Routes
	}
	return nil
}

type RouteDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Auth          string                 `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteDescriptor) Reset() {
	*x = RouteDescriptor{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteDescriptor) ProtoMessage() {}

func (x *RouteDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteDescriptor.ProtoReflect.Descriptor instead.
func (*RouteDescriptor) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *RouteDescriptor) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RouteDescriptor) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RouteDescriptor) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *RouteDescriptor) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

// Handle API request/response
type HandleAPIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         map[string]*StringList `protobuf:"bytes,3,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Headers       map[string]*StringList `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	UserId        *int64                 `protobuf:"varint,6,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,7,rep,name=scopes,proto3" json:"scopes,omitempty"`
	SdkServerId   uint32                 `protobuf:"varint,8,opt,name=sdk_server_id,json=sdkServerId,proto3" json:"sdk_server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleAPIRequest) Reset() {
	*x = HandleAPIRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleAPIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleAPIRequest) ProtoMessage() {}

func (x *HandleAPIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleAPIRequest.ProtoReflect.Descriptor instead.
func (*HandleAPIRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HandleAPIRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HandleAPIRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HandleAPIRequest) GetQuery() map[string]*StringList {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *HandleAPIRequest) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HandleAPIRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HandleAPIRequest) GetUserId() int64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *HandleAPIRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *HandleAPIRequest) GetSdkServerId() uint32 {
	if x != nil {
		return x.SdkServerId
	}
	return 0
}

type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type HandleAPIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       map[string]*StringList `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleAPIResponse) Reset() {
	*x = HandleAPIResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleAPIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleAPIResponse) ProtoMessage() {}

func (x *HandleAPIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleAPIResponse.ProtoReflect.Descriptor instead.
func (*HandleAPIResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *HandleAPIResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HandleAPIResponse) GetHeaders() map[string]*StringList {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HandleAPIResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// UI Manifest response
type UIManifestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NavItems      []*UINavItem           `protobuf:"bytes,1,rep,name=nav_items,json=navItems,proto3" json:"nav_items,omitempty"`
	Routes        []*UIRoute             `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIManifestResponse) Reset() {
	*x = UIManifestResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIManifestResponse) ProtoMessage() {}

func (x *UIManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIManifestResponse.ProtoReflect.Descriptor instead.
func (*UIManifestResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *UIManifestResponse) GetNavItems() []*UINavItem {
	if x != nil {
		return x.NavItems
	}
	return nil
}

func (x *UIManifestResponse) GetRoutes() []*UIRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

type UINavItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Group         string                 `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UINavItem) Reset() {
	*x = UINavItem{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UINavItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UINavItem) ProtoMessage() {}

func (x *UINavItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UINavItem.ProtoReflect.Descriptor instead.
func (*UINavItem) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *UINavItem) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UINavItem) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UINavItem) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *UINavItem) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type UIRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BundleUrl     string                 `protobuf:"bytes,2,opt,name=bundle_url,json=bundleUrl,proto3" json:"bundle_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UIRoute) Reset() {
	*x = UIRoute{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UIRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UIRoute) ProtoMessage() {}

func (x *UIRoute) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UIRoute.ProtoReflect.Descriptor instead.
func (*UIRoute) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *UIRoute) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UIRoute) GetBundleUrl() string {
	if x != nil {
		return x.BundleUrl
	}
	return ""
}

// Event handling
type HandleEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"` // JSON-encoded map
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleEventRequest) Reset() {
	*x = HandleEventRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleEventRequest) ProtoMessage() {}

func (x *HandleEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleEventRequest.ProtoReflect.Descriptor instead.
func (*HandleEventRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *HandleEventRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *HandleEventRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HandleEventRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HandleEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleEventResponse) Reset() {
	*x = HandleEventResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleEventResponse) ProtoMessage() {}

func (x *HandleEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleEventResponse.ProtoReflect.Descriptor instead.
func (*HandleEventResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *HandleEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleEventResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// SDK Config methods
type ConfigGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetRequest) Reset() {
	*x = ConfigGetRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetRequest) ProtoMessage() {}

func (x *ConfigGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetRequest.ProtoReflect.Descriptor instead.
func (*ConfigGetRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ConfigGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded value
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetResponse) Reset() {
	*x = ConfigGetResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetResponse) ProtoMessage() {}

func (x *ConfigGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetResponse.ProtoReflect.Descriptor instead.
func (*ConfigGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ConfigGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ConfigGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigGetStringRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetStringRequest) Reset() {
	*x = ConfigGetStringRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetStringRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetStringRequest) ProtoMessage() {}

func (x *ConfigGetStringRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetStringRequest.ProtoReflect.Descriptor instead.
func (*ConfigGetStringRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *ConfigGetStringRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ConfigGetStringResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigGetStringResponse) Reset() {
	*x = ConfigGetStringResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigGetStringResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigGetStringResponse) ProtoMessage() {}

func (x *ConfigGetStringResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigGetStringResponse.ProtoReflect.Descriptor instead.
func (*ConfigGetStringResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *ConfigGetStringResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ConfigGetStringResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // JSON-encoded value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSetRequest) Reset() {
	*x = ConfigSetRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetRequest) ProtoMessage() {}

func (x *ConfigSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetRequest.ProtoReflect.Descriptor instead.
func (*ConfigSetRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *ConfigSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ConfigSetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ConfigSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSetResponse) Reset() {
	*x = ConfigSetResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSetResponse) ProtoMessage() {}

func (x *ConfigSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSetResponse.ProtoReflect.Descriptor instead.
func (*ConfigSetResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *ConfigSetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfigDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDeleteRequest) Reset() {
	*x = ConfigDeleteRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDeleteRequest) ProtoMessage() {}

func (x *ConfigDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDeleteRequest.ProtoReflect.Descriptor instead.
func (*ConfigDeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *ConfigDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ConfigDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigDeleteResponse) Reset() {
	*x = ConfigDeleteResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigDeleteResponse) ProtoMessage() {}

func (x *ConfigDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigDeleteResponse.ProtoReflect.Descriptor instead.
func (*ConfigDeleteResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *ConfigDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Indexer methods
type IsIndexerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsIndexerRequest) Reset() {
	*x = IsIndexerRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsIndexerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsIndexerRequest) ProtoMessage() {}

func (x *IsIndexerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsIndexerRequest.ProtoReflect.Descriptor instead.
func (*IsIndexerRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{22}
}

type IsIndexerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsIndexer     bool                   `protobuf:"varint,1,opt,name=is_indexer,json=isIndexer,proto3" json:"is_indexer,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsIndexerResponse) Reset() {
	*x = IsIndexerResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsIndexerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsIndexerResponse) ProtoMessage() {}

func (x *IsIndexerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsIndexerResponse.ProtoReflect.Descriptor instead.
func (*IsIndexerResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *IsIndexerResponse) GetIsIndexer() bool {
	if x != nil {
		return x.IsIndexer
	}
	return false
}

func (x *IsIndexerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Downloader methods
type IsDownloaderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDownloaderRequest) Reset() {
	*x = IsDownloaderRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDownloaderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDownloaderRequest) ProtoMessage() {}

func (x *IsDownloaderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDownloaderRequest.ProtoReflect.Descriptor instead.
func (*IsDownloaderRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{24}
}

type IsDownloaderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsDownloader  bool                   `protobuf:"varint,1,opt,name=is_downloader,json=isDownloader,proto3" json:"is_downloader,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsDownloaderResponse) Reset() {
	*x = IsDownloaderResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsDownloaderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsDownloaderResponse) ProtoMessage() {}

func (x *IsDownloaderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsDownloaderResponse.ProtoReflect.Descriptor instead.
func (*IsDownloaderResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *IsDownloaderResponse) GetIsDownloader() bool {
	if x != nil {
		return x.IsDownloader
	}
	return false
}

func (x *IsDownloaderResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IndexerSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Categories    []string               `protobuf:"bytes,3,rep,name=categories,proto3" json:"categories,omitempty"`
	Tvdbid        string                 `protobuf:"bytes,4,opt,name=tvdbid,proto3" json:"tvdbid,omitempty"`
	Tvrageid      string                 `protobuf:"bytes,5,opt,name=tvrageid,proto3" json:"tvrageid,omitempty"`
	Season        int32                  `protobuf:"varint,6,opt,name=season,proto3" json:"season,omitempty"`
	Episode       int32                  `protobuf:"varint,7,opt,name=episode,proto3" json:"episode,omitempty"`
	Imdbid        string                 `protobuf:"bytes,8,opt,name=imdbid,proto3" json:"imdbid,omitempty"`
	Tmdbid        string                 `protobuf:"bytes,9,opt,name=tmdbid,proto3" json:"tmdbid,omitempty"`
	Limit         int32                  `protobuf:"varint,10,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,11,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexerSearchRequest) Reset() {
	*x = IndexerSearchRequest{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexerSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexerSearchRequest) ProtoMessage() {}

func (x *IndexerSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexerSearchRequest.ProtoReflect.Descriptor instead.
func (*IndexerSearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *IndexerSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *IndexerSearchRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *IndexerSearchRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *IndexerSearchRequest) GetTvdbid() string {
	if x != nil {
		return x.Tvdbid
	}
	return ""
}

func (x *IndexerSearchRequest) GetTvrageid() string {
	if x != nil {
		return x.Tvrageid
	}
	return ""
}

func (x *IndexerSearchRequest) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

func (x *IndexerSearchRequest) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *IndexerSearchRequest) GetImdbid() string {
	if x != nil {
		return x.Imdbid
	}
	return ""
}

func (x *IndexerSearchRequest) GetTmdbid() string {
	if x != nil {
		return x.Tmdbid
	}
	return ""
}

func (x *IndexerSearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *IndexerSearchRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type IndexerSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Releases      []*IndexerRelease      `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	IndexerId     string                 `protobuf:"bytes,3,opt,name=indexer_id,json=indexerId,proto3" json:"indexer_id,omitempty"`
	IndexerName   string                 `protobuf:"bytes,4,opt,name=indexer_name,json=indexerName,proto3" json:"indexer_name,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexerSearchResponse) Reset() {
	*x = IndexerSearchResponse{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexerSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexerSearchResponse) ProtoMessage() {}

func (x *IndexerSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexerSearchResponse.ProtoReflect.Descriptor instead.
func (*IndexerSearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{27}
}

func (x *IndexerSearchResponse) GetReleases() []*IndexerRelease {
	if x != nil {
		return x.Releases
	}
	return nil
}

func (x *IndexerSearchResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *IndexerSearchResponse) GetIndexerId() string {
	if x != nil {
		return x.IndexerId
	}
	return ""
}

func (x *IndexerSearchResponse) GetIndexerName() string {
	if x != nil {
		return x.IndexerName
	}
	return ""
}

func (x *IndexerSearchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IndexerRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Comments      string                 `protobuf:"bytes,4,opt,name=comments,proto3" json:"comments,omitempty"`
	PublishDate   int64                  `protobuf:"varint,5,opt,name=publish_date,json=publishDate,proto3" json:"publish_date,omitempty"` // Unix timestamp
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Size          int64                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`
	DownloadUrl   string                 `protobuf:"bytes,8,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,10,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IndexerId     string                 `protobuf:"bytes,11,opt,name=indexer_id,json=indexerId,proto3" json:"indexer_id,omitempty"`
	IndexerName   string                 `protobuf:"bytes,12,opt,name=indexer_name,json=indexerName,proto3" json:"indexer_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexerRelease) Reset() {
	*x = IndexerRelease{}
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexerRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexerRelease) ProtoMessage() {}

func (x *IndexerRelease) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugins_proto_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexerRelease.ProtoReflect.Descriptor instead.
func (*IndexerRelease) Descriptor() ([]byte, []int) {
	return file_internal_plugins_proto_plugin_proto_rawDescGZIP(), []int{28}
}

func (x *IndexerRelease) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *IndexerRelease) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *IndexerRelease) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *IndexerRelease) GetComments() string {
	if x != nil {
		return x.Comments
	}
	return ""
}

func (x *IndexerRelease) GetPublishDate() int64 {
	if x != nil {
		return x.PublishDate
	}
	return 0
}

func (x *IndexerRelease) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *IndexerRelease) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *IndexerRelease) GetDownloadUrl() string {
	if x != nil {
		return x.DownloadUrl
	}
	return ""
}

func (x *IndexerRelease) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IndexerRelease) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *IndexerRelease) GetIndexerId() string {
	if x != nil {
		return x.IndexerId
	}
	return ""
}

func (x *IndexerRelease) GetIndexerName() string {
	if x != nil {
		return x.IndexerName
	}
	return ""
}

var File_internal_plugins_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_plugins_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"#internal/plugins/proto/plugin.proto\x12\x05proto\"\x11\n" +
	"\x0fMetadataRequest\"\x12\n" +
	"\x10APIRoutesRequest\"\x13\n" +
	"\x11UIManifestRequest\"\x96\x01\n" +
	"\x10MetadataResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\fcapabilities\x18\x05 \x03(\tR\fcapabilities\"C\n" +
	"\x11APIRoutesResponse\x12.\n" +
	"\x06routes\x18\x01 \x03(\v2\x16.proto.RouteDescriptorR\x06routes\"c\n" +
	"\x0fRouteDescriptor\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04auth\x18\x03 \x01(\tR\x04auth\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\"\xce\x03\n" +
	"\x10HandleAPIRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x128\n" +
	"\x05query\x18\x03 \x03(\v2\".proto.HandleAPIRequest.QueryEntryR\x05query\x12>\n" +
	"\aheaders\x18\x04 \x03(\v2$.proto.HandleAPIRequest.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\x12\x1c\n" +
	"\auser_id\x18\x06 \x01(\x03H\x00R\x06userId\x88\x01\x01\x12\x16\n" +
	"\x06scopes\x18\a \x03(\tR\x06scopes\x12\"\n" +
	"\rsdk_server_id\x18\b \x01(\rR\vsdkServerId\x1aK\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.StringListR\x05value:\x028\x01\x1aM\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.StringListR\x05value:\x028\x01B\n" +
	"\n" +
	"\b_user_id\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xd8\x01\n" +
	"\x11HandleAPIResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12?\n" +
	"\aheaders\x18\x02 \x03(\v2%.proto.HandleAPIResponse.HeadersEntryR\aheaders\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x1aM\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.proto.StringListR\x05value:\x028\x01\"k\n" +
	"\x12UIManifestResponse\x12-\n" +
	"\tnav_items\x18\x01 \x03(\v2\x10.proto.UINavItemR\bnavItems\x12&\n" +
	"\x06routes\x18\x02 \x03(\v2\x0e.proto.UIRouteR\x06routes\"_\n" +
	"\tUINavItem\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05group\x18\x03 \x01(\tR\x05group\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\"<\n" +
	"\aUIRoute\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1d\n" +
	"\n" +
	"bundle_url\x18\x02 \x01(\tR\tbundleUrl\"Z\n" +
	"\x12HandleEventRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"E\n" +
	"\x13HandleEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"$\n" +
	"\x10ConfigGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"?\n" +
	"\x11ConfigGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"*\n" +
	"\x16ConfigGetStringRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"E\n" +
	"\x17ConfigGetStringResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\":\n" +
	"\x10ConfigSetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\")\n" +
	"\x11ConfigSetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"'\n" +
	"\x13ConfigDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\",\n" +
	"\x14ConfigDeleteResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\x12\n" +
	"\x10IsIndexerRequest\"H\n" +
	"\x11IsIndexerResponse\x12\x1d\n" +
	"\n" +
	"is_indexer\x18\x01 \x01(\bR\tisIndexer\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x15\n" +
	"\x13IsDownloaderRequest\"Q\n" +
	"\x14IsDownloaderResponse\x12#\n" +
	"\ris_downloader\x18\x01 \x01(\bR\fisDownloader\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xa4\x02\n" +
	"\x14IndexerSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1e\n" +
	"\n" +
	"categories\x18\x03 \x03(\tR\n" +
	"categories\x12\x16\n" +
	"\x06tvdbid\x18\x04 \x01(\tR\x06tvdbid\x12\x1a\n" +
	"\btvrageid\x18\x05 \x01(\tR\btvrageid\x12\x16\n" +
	"\x06season\x18\x06 \x01(\x05R\x06season\x12\x18\n" +
	"\aepisode\x18\a \x01(\x05R\aepisode\x12\x16\n" +
	"\x06imdbid\x18\b \x01(\tR\x06imdbid\x12\x16\n" +
	"\x06tmdbid\x18\t \x01(\tR\x06tmdbid\x12\x14\n" +
	"\x05limit\x18\n" +
	" \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\v \x01(\x05R\x06offset\"\xb8\x01\n" +
	"\x15IndexerSearchResponse\x121\n" +
	"\breleases\x18\x01 \x03(\v2\x15.proto.IndexerReleaseR\breleases\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x1d\n" +
	"\n" +
	"indexer_id\x18\x03 \x01(\tR\tindexerId\x12!\n" +
	"\findexer_name\x18\x04 \x01(\tR\vindexerName\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xca\x03\n" +
	"\x0eIndexerRelease\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x1a\n" +
	"\bcomments\x18\x04 \x01(\tR\bcomments\x12!\n" +
	"\fpublish_date\x18\x05 \x01(\x03R\vpublishDate\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x12\n" +
	"\x04size\x18\a \x01(\x03R\x04size\x12!\n" +
	"\fdownload_url\x18\b \x01(\tR\vdownloadUrl\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12E\n" +
	"\n" +
	"attributes\x18\n" +
	" \x03(\v2%.proto.IndexerRelease.AttributesEntryR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"indexer_id\x18\v \x01(\tR\tindexerId\x12!\n" +
	"\findexer_name\x18\f \x01(\tR\vindexerName\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa3\x04\n" +
	"\rPluginService\x12;\n" +
	"\bMetadata\x12\x16.proto.MetadataRequest\x1a\x17.proto.MetadataResponse\x12>\n" +
	"\tAPIRoutes\x12\x17.proto.APIRoutesRequest\x1a\x18.proto.APIRoutesResponse\x12>\n" +
	"\tHandleAPI\x12\x17.proto.HandleAPIRequest\x1a\x18.proto.HandleAPIResponse\x12A\n" +
	"\n" +
	"UIManifest\x12\x18.proto.UIManifestRequest\x1a\x19.proto.UIManifestResponse\x12D\n" +
	"\vHandleEvent\x12\x19.proto.HandleEventRequest\x1a\x1a.proto.HandleEventResponse\x12>\n" +
	"\tIsIndexer\x12\x17.proto.IsIndexerRequest\x1a\x18.proto.IsIndexerResponse\x12C\n" +
	"\x06Search\x12\x1b.proto.IndexerSearchRequest\x1a\x1c.proto.IndexerSearchResponse\x12G\n" +
	"\fIsDownloader\x12\x1a.proto.IsDownloaderRequest\x1a\x1b.proto.IsDownloaderResponse2\xa7\x02\n" +
	"\n" +
	"SDKService\x12>\n" +
	"\tConfigGet\x12\x17.proto.ConfigGetRequest\x1a\x18.proto.ConfigGetResponse\x12P\n" +
	"\x0fConfigGetString\x12\x1d.proto.ConfigGetStringRequest\x1a\x1e.proto.ConfigGetStringResponse\x12>\n" +
	"\tConfigSet\x12\x17.proto.ConfigSetRequest\x1a\x18.proto.ConfigSetResponse\x12G\n" +
	"\fConfigDelete\x12\x1a.proto.ConfigDeleteRequest\x1a\x1b.proto.ConfigDeleteResponseB9Z7github.com/blakestevenson/nimbus/internal/plugins/protob\x06proto3"

var (
	file_internal_plugins_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_plugins_proto_plugin_proto_rawDescData []byte
)

func file_internal_plugins_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_plugins_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_plugins_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugins_proto_plugin_proto_rawDesc), len(file_internal_plugins_proto_plugin_proto_rawDesc)))
	})
	return file_internal_plugins_proto_plugin_proto_rawDescData
}

var file_internal_plugins_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_internal_plugins_proto_plugin_proto_goTypes = []any{
	(*MetadataRequest)(nil),         // 0: proto.MetadataRequest
	(*APIRoutesRequest)(nil),        // 1: proto.APIRoutesRequest
	(*UIManifestRequest)(nil),       // 2: proto.UIManifestRequest
	(*MetadataResponse)(nil),        // 3: proto.MetadataResponse
	(*APIRoutesResponse)(nil),       // 4: proto.APIRoutesResponse
	(*RouteDescriptor)(nil),         // 5: proto.RouteDescriptor
	(*HandleAPIRequest)(nil),        // 6: proto.HandleAPIRequest
	(*StringList)(nil),              // 7: proto.StringList
	(*HandleAPIResponse)(nil),       // 8: proto.HandleAPIResponse
	(*UIManifestResponse)(nil),      // 9: proto.UIManifestResponse
	(*UINavItem)(nil),               // 10: proto.UINavItem
	(*UIRoute)(nil),                 // 11: proto.UIRoute
	(*HandleEventRequest)(nil),      // 12: proto.HandleEventRequest
	(*HandleEventResponse)(nil),     // 13: proto.HandleEventResponse
	(*ConfigGetRequest)(nil),        // 14: proto.ConfigGetRequest
	(*ConfigGetResponse)(nil),       // 15: proto.ConfigGetResponse
	(*ConfigGetStringRequest)(nil),  // 16: proto.ConfigGetStringRequest
	(*ConfigGetStringResponse)(nil), // 17: proto.ConfigGetStringResponse
	(*ConfigSetRequest)(nil),        // 18: proto.ConfigSetRequest
	(*ConfigSetResponse)(nil),       // 19: proto.ConfigSetResponse
	(*ConfigDeleteRequest)(nil),     // 20: proto.ConfigDeleteRequest
	(*ConfigDeleteResponse)(nil),    // 21: proto.ConfigDeleteResponse
	(*IsIndexerRequest)(nil),        // 22: proto.IsIndexerRequest
	(*IsIndexerResponse)(nil),       // 23: proto.IsIndexerResponse
	(*IsDownloaderRequest)(nil),     // 24: proto.IsDownloaderRequest
	(*IsDownloaderResponse)(nil),    // 25: proto.IsDownloaderResponse
	(*IndexerSearchRequest)(nil),    // 26: proto.IndexerSearchRequest
	(*IndexerSearchResponse)(nil),   // 27: proto.IndexerSearchResponse
	(*IndexerRelease)(nil),          // 28: proto.IndexerRelease
	nil,                             // 29: proto.HandleAPIRequest.QueryEntry
	nil,                             // 30: proto.HandleAPIRequest.HeadersEntry
	nil,                             // 31: proto.HandleAPIResponse.HeadersEntry
	nil,                             // 32: proto.IndexerRelease.AttributesEntry
}
var file_internal_plugins_proto_plugin_proto_depIdxs = []int32{
	5,  // 0: proto.APIRoutesResponse.routes:type_name -> proto.RouteDescriptor
	29, // 1: proto.HandleAPIRequest.query:type_name -> proto.HandleAPIRequest.QueryEntry
	30, // 2: proto.HandleAPIRequest.headers:type_name -> proto.HandleAPIRequest.HeadersEntry
	31, // 3: proto.HandleAPIResponse.headers:type_name -> proto.HandleAPIResponse.HeadersEntry
	10, // 4: proto.UIManifestResponse.nav_items:type_name -> proto.UINavItem
	11, // 5: proto.UIManifestResponse.routes:type_name -> proto.UIRoute
	28, // 6: proto.IndexerSearchResponse.releases:type_name -> proto.IndexerRelease
	32, // 7: proto.IndexerRelease.attributes:type_name -> proto.IndexerRelease.AttributesEntry
	7,  // 8: proto.HandleAPIRequest.QueryEntry.value:type_name -> proto.StringList
	7,  // 9: proto.HandleAPIRequest.HeadersEntry.value:type_name -> proto.StringList
	7,  // 10: proto.HandleAPIResponse.HeadersEntry.value:type_name -> proto.StringList
	0,  // 11: proto.PluginService.Metadata:input_type -> proto.MetadataRequest
	1,  // 12: proto.PluginService.APIRoutes:input_type -> proto.APIRoutesRequest
	6,  // 13: proto.PluginService.HandleAPI:input_type -> proto.HandleAPIRequest
	2,  // 14: proto.PluginService.UIManifest:input_type -> proto.UIManifestRequest
	12, // 15: proto.PluginService.HandleEvent:input_type -> proto.HandleEventRequest
	22, // 16: proto.PluginService.IsIndexer:input_type -> proto.IsIndexerRequest
	26, // 17: proto.PluginService.Search:input_type -> proto.IndexerSearchRequest
	24, // 18: proto.PluginService.IsDownloader:input_type -> proto.IsDownloaderRequest
	14, // 19: proto.SDKService.ConfigGet:input_type -> proto.ConfigGetRequest
	16, // 20: proto.SDKService.ConfigGetString:input_type -> proto.ConfigGetStringRequest
	18, // 21: proto.SDKService.ConfigSet:input_type -> proto.ConfigSetRequest
	20, // 22: proto.SDKService.ConfigDelete:input_type -> proto.ConfigDeleteRequest
	3,  // 23: proto.PluginService.Metadata:output_type -> proto.MetadataResponse
	4,  // 24: proto.PluginService.APIRoutes:output_type -> proto.APIRoutesResponse
	8,  // 25: proto.PluginService.HandleAPI:output_type -> proto.HandleAPIResponse
	9,  // 26: proto.PluginService.UIManifest:output_type -> proto.UIManifestResponse
	13, // 27: proto.PluginService.HandleEvent:output_type -> proto.HandleEventResponse
	23, // 28: proto.PluginService.IsIndexer:output_type -> proto.IsIndexerResponse
	27, // 29: proto.PluginService.Search:output_type -> proto.IndexerSearchResponse
	25, // 30: proto.PluginService.IsDownloader:output_type -> proto.IsDownloaderResponse
	15, // 31: proto.SDKService.ConfigGet:output_type -> proto.ConfigGetResponse
	17, // 32: proto.SDKService.ConfigGetString:output_type -> proto.ConfigGetStringResponse
	19, // 33: proto.SDKService.ConfigSet:output_type -> proto.ConfigSetResponse
	21, // 34: proto.SDKService.ConfigDelete:output_type -> proto.ConfigDeleteResponse
	23, // [23:35] is the sub-list for method output_type
	11, // [11:23] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_internal_plugins_proto_plugin_proto_init() }
func file_internal_plugins_proto_plugin_proto_init() {
	if File_internal_plugins_proto_plugin_proto != nil {
		return
	}
	file_internal_plugins_proto_plugin_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugins_proto_plugin_proto_rawDesc), len(file_internal_plugins_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_plugins_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_plugins_proto_plugin_proto_depIdxs,
		MessageInfos:      file_internal_plugins_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_plugins_proto_plugin_proto = out.File
	file_internal_plugins_proto_plugin_proto_goTypes = nil
	file_internal_plugins_proto_plugin_proto_depIdxs = nil
}
